import 'package:flutter/material.dart';

extension BuildContextExt on BuildContext {
  // Theme shortcut
  ThemeData get theme => Theme.of(this);
  TextTheme get textTheme => theme.textTheme;
  ColorScheme get colorScheme => theme.colorScheme;

  // MediaQuery shortcuts
  double get screenWidth => MediaQuery.of(this).size.width;
  double get screenHeight => MediaQuery.of(this).size.height;

  // Snackbar helper
  void showSnackBar(String message, {bool isError = false}) {
    ScaffoldMessenger.of(this)
      ..hideCurrentSnackBar()
      ..showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: isError ? colorScheme.error : colorScheme.primary,
          behavior: SnackBarBehavior.floating,
        ),
      );
  }
}

extension StringFormatter on String {
  /// Cleans LaTeX math/temperature formats generated by AI models
  /// (e.g., $2^{\circ}\text{C}$ -> 2°C) into standard Unicode characters.
  String cleanAiResponse() {
    var cleaned = this;

    // 1. Convert Celsius/Fahrenheit LaTeX to simple format
    // Matches $2^{\circ}\text{C}$ or $2^\circ\text{C}$ or $2^\circ C$ or variations with F
    cleaned = cleaned.replaceAllMapped(
      RegExp(
        r'\$?(\d+(?:\.\d+)?)\s*(?:\^{\\circ}|\^\\circ|{\\circ}|\\circ)\s*(?:\\text\{([CF])\}|([CF]))\$?',
      ),
      (match) {
        final num = match[1];
        final unit = match[2] ?? match[3] ?? 'C';
        return '$num°$unit';
      },
    );

    // 2. Convert standard degree LaTeX
    // Matches $90^{\circ}$ or $90^\circ$ or $90\circ$
    cleaned = cleaned.replaceAllMapped(
      RegExp(
        r'\$?(\d+(?:\.\d+)?)\s*(?:\^{\\circ}|\^\\circ|{\\circ}|\\circ)\$?',
      ),
      (match) {
        final num = match[1];
        return '$num°';
      },
    );

    // 3. Convert basic LaTeX math operators
    cleaned = cleaned.replaceAll(r'\leq', '≤');
    cleaned = cleaned.replaceAll(r'\le', '≤');
    cleaned = cleaned.replaceAll(r'\geq', '≥');
    cleaned = cleaned.replaceAll(r'\ge', '≥');
    cleaned = cleaned.replaceAll(r'\pm', '±');
    cleaned = cleaned.replaceAll(r'\times', '×');
    cleaned = cleaned.replaceAll(r'\approx', '≈');
    cleaned = cleaned.replaceAll(r'\neq', '≠');

    // 4. Remove \text{...} wrappers
    cleaned = cleaned.replaceAllMapped(
      RegExp(r'\\text\{([^}]+)\}'),
      (match) => match[1]!,
    );

    // 5. Remove math mode dollars around single variables or numbers
    // Matches $x$ or $2$ but not complex math blocks
    cleaned = cleaned.replaceAllMapped(RegExp(r'\$([^$]+)\$'), (match) {
      final inner = match[1]!;
      if (!inner.contains('\\') &&
          !inner.contains('_') &&
          !inner.contains('^')) {
        return inner;
      }
      return match[0]!;
    });

    return cleaned;
  }
}
